on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '21.0.5'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.24.3'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release
    - run : flutter build ipa -no-codesign
    - run : |
        cd build
        tar -czf ios_build.tar.gz ios
    - uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/ios_build.tar.gz
          
    